export { default as AppHeader } from './AppHeader.vue'
export { default as PostCard } from './PostCard.vue'
export { default as PostWidget } from './PostWidget.vue'
export { default as CategoriesWidget } from './CategoriesWidget.vue'
export { default as PostContent } from './PostContent.vue'
export { default as Author } from './Author.vue'
export { default as CommentsForm } from './CommentsForm.vue'
